name: Render Website Video

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Website URL to render'
        required: true
        type: string
      jobId:
        description: 'Unique job ID'
        required: true
        type: string
      duration:
        description: 'Video duration in frames'
        required: false
        type: string
        default: '300'

jobs:
  render-video:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install Remotion CLI
      run: npm install -g @remotion/cli
      
    - name: Render video
      run: |
        npx remotion render src/index.tsx WebsiteVideo "video-${{ github.event.inputs.jobId }}.mp4" \
          --props='{"url":"${{ github.event.inputs.url }}","duration":${{ github.event.inputs.duration }}}'
        
    - name: Upload video as artifact
      uses: actions/upload-artifact@v4
      with:
        name: video-${{ github.event.inputs.jobId }}
        path: video-${{ github.event.inputs.jobId }}.mp4
        retention-days: 1
        
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: video-${{ github.event.inputs.jobId }}
        release_name: Video ${{ github.event.inputs.jobId }}
        draft: false
        prerelease: false
        
    - name: Upload video to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./video-${{ github.event.inputs.jobId }}.mp4
        asset_name: video-${{ github.event.inputs.jobId }}.mp4
        asset_content_type: video/mp4 