name: Render Website Video

on:
  push:
    branches:
      - changes
  workflow_dispatch:
    inputs:
      url:
        description: 'Website URL to render'
        required: true
        type: string
      durationInFrames:
        description: 'Video duration in frames'
        required: true
        type: string

permissions:
  contents: write
  actions: read

jobs:
  render-video:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ./backend/package-lock.json
        
    - name: Install dependencies
      run: npm install
      working-directory: ./backend
      
    - name: Install Remotion CLI
      run: npm install -g @remotion/cli
      working-directory: ./backend
      
    - name: Render video
      run: |
        npx remotion render src/index.tsx WebsiteVideo "videos/output.mp4" \
          --props='{"url":"${{ github.event.inputs.url }}"}' \
          --duration-in-frames=${{ github.event.inputs.durationInFrames }}
      working-directory: ./backend
        
    - name: List files in backend
      run: ls -lh
      working-directory: ./backend
        
    - name: Upload video as artifact
      uses: actions/upload-artifact@v4
      with:
        name: video-${{ github.event.inputs.durationInFrames }}
        path: backend/videos/output.mp4
        retention-days: 1

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: video-${{ github.event.inputs.durationInFrames }}
        name: Video ${{ github.event.inputs.durationInFrames }}
        draft: false
        prerelease: false
        files: backend/videos/output.mp4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Notify backend of video completion
      run: |
        curl -X POST ${{ secrets.WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d '{"jobId":"${{ github.event.inputs.durationInFrames }}","videoUrl":"https://github.com/${{ github.repository }}/releases/download/video-${{ github.event.inputs.durationInFrames }}/output.mp4"}' 