name: Render Website Video

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Website URL to render'
        required: true
        type: string
      jobId:
        description: 'Unique job ID'
        required: true
        type: string
      duration:
        description: 'Video duration in frames'
        required: false
        type: string
        default: '300'

permissions:
  contents: write
  actions: read

jobs:
  render-video:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ./backend/package-lock.json
        
    - name: Install dependencies
      run: npm install
      working-directory: ./backend
      
    - name: Install Remotion CLI
      run: npm install -g @remotion/cli
      working-directory: ./backend
      
    - name: Render video
      run: |
        npx remotion render src/index.tsx WebsiteVideo "videos/video-${{ github.event.inputs.jobId }}.mp4" \
          --props='{"url":"${{ github.event.inputs.url }}","duration":${{ github.event.inputs.duration }}}'
      working-directory: ./backend
        
    - name: List files in backend
      run: ls -lh
      working-directory: ./backend
        
    - name: Upload video as artifact
      uses: actions/upload-artifact@v4
      with:
        name: video-${{ github.event.inputs.jobId }}
        path: backend/videos/video-${{ github.event.inputs.jobId }}.mp4
        retention-days: 1

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: video-${{ github.event.inputs.jobId }}
        name: Video ${{ github.event.inputs.jobId }}
        draft: false
        prerelease: false
        files: backend/videos/video-${{ github.event.inputs.jobId }}.mp4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set job id
      id: set_job_id
      run: echo "::set-output name=job_id::${{ github.run_id }}"

    - name: Set video url
      id: set_video_url
      run: echo "::set-output name=video_url::https://github.com/${{ github.repository }}/releases/download/video-${{ github.run_id }}/video-${{ github.run_id }}.mp4"

    - name: Notify backend of video completion
      run: |
        curl -X POST "https://websiterendering-production.up.railway.app/api/video-complete" \
          -H "Content-Type: application/json" \
          -d '{"jobId":"${{ github.event.inputs.jobId }}","videoUrl":"${{ steps.set_video_url.outputs.video_url }}"}' 